In [1]:
%load_ext watermark
%watermark -a "Alessandro Parisi" -u -d -v -p numpy,pandas,matplotlib,sklearn,seaborn
# to install watermark launch 'pip install watermark' at command line
import warnings 
warnings.simplefilter('ignore')

Alessandro Parisi 
last updated: 2019-04-17 

CPython 3.5.4
IPython 6.1.0

numpy 1.15.2
pandas 0.23.4
matplotlib 2.2.2
sklearn 0.20.0
seaborn 0.8.0


In [2]:
import numpy as np

X = np.array([
 [3, 0.1, -2.4],
 [3.1, 0.3, -2.6],
 [3.4, 0.2, -1.9],
])

print(np.cov(X).T)

[[7.30333333 7.69166667 7.19166667]
 [7.69166667 8.12333333 7.54333333]
 [7.19166667 7.54333333 7.12333333]]


In [5]:
"""
     __        __    
    |            |   
    | 2       -4 |  
A = |            |  
    | 4       -6 |  
    |__        __| 
    

"""


import numpy as np
eigenvaules, eigenvectors = np.linalg.eig(np.array([[2, -4], [4, -6]]))

print("Eigenvaules:", eigenvaules)
print("Eigenvectors:", eigenvectors)

Eigenvaules: [-1.99999996 -2.00000004]
Eigenvectors: [[0.70710678 0.70710678]
 [0.70710678 0.70710678]]
